const speciesEmojiMap: Record<string, string> = {
  'Aeschynanthus radicans': '🌺',
  'Aglaonema commutatum': '🍃',
  'Alocasia reginula': '🪴',
  'Alocasia zebrina': '🌿',
  'Aloe vera': '🌱',
  'Anthurium andraeanum': '🌹',
  'Anthurium clarinervium': '🍃',
  'Aspidistra elatior': '🌿',
  'Beaucarnea recurvata': '🌴',
  'Begonia rex': '🪻',
  'Ceropegia woodii': '💚',
  'Chamaedorea elegans': '🌴',
  'Chlorophytum comosum': '🌱',
  'Chrysalidocarpus lutescens': '🌴',
  'Codiaeum variegatum': '🍂',
  'Colocasia esculenta': '🍃',
  'Coriandrum sativum': '🍀',
  'Crassula ovata': '🪴',
  'Ctenanthe burle-marxii': '🌿',
  'Curio rowleyanus': '🫛',
  'Cyclamen persicum': '🌸',
  'Cymbidium goeringii': '🪷',
  'Dendrobium nobile': '🌼',
  'Dieffenbachia seguine': '🍃',
  'Dischidia nummularia': '☘️',
  'Dracaena fragrans': '🎋',
  'Dracaena reflexa var. angustifolia': '🌲',
  'Dracaena trifasciata': '🪴',
  'Echeveria elegans': '🌸',
  'Epipremnum aureum': '🍃',
  'Ficus elastica': '🌳',
  'Ficus lyrata': '🍃',
  'Gardenia jasminoides': '🌼',
  'Gerbera jamesonii': '🌻',
  'Goeppertia makoyana': '🌿',
  'Goeppertia orbifolia': '🍃',
  'Gymnocalycium mihanovichii': '🌵',
  'Haworthia cooperi': '💧',
  'Haworthiopsis attenuata': '🌱',
  'Heptapleurum arboricola': '🌳',
  'Hibiscus rosa-sinensis': '🌺',
  'Hoya carnosa': '🌸',
  'Hydrangea macrophylla': '🪻',
  'Kalanchoe blossfeldiana': '🌼',
  'Mammillaria elongata': '🌵',
  'Maranta leuconeura': '🌿',
  'Mentha spicata': '🍃',
  'Mentha suaveolens': '🌱',
  'Monstera adansonii': '☘️',
  'Monstera deliciosa': '🌿',
  'Ocimum basilicum': '🌿',
  'Opuntia microdasys': '🌵',
  'Origanum vulgare': '☘️',
  'Pachira aquatica': '🌳',
  'Paphiopedilum insigne': '🪷',
  'Pelargonium zonale': '🌺',
  'Peperomia caperata': '🍀',
  'Peperomia obtusifolia': '🌱',
  'Petroselinum crispum': '🌿',
  'Phalaenopsis amabilis': '🌸',
  'Phalaenopsis aphrodite': '🪷',
  'Philodendron erubescens': '🍃',
  'Philodendron gloriosum': '🌿',
  'Philodendron hederaceum': '☘️',
  'Philodendron melanochrysum': '🍂',
  'Pilea peperomioides': '🍀',
  'Rhaphidophora tetrasperma': '🌱',
  'Rhipsalis baccifera': '🎋',
  'Salvia rosmarinus': '🌱',
  'Schlumbergera truncata': '🌺',
  'Scindapsus pictus': '🍃',
  'Sedum rubrotinctum': '🫛',
  'Spathiphyllum wallisii': '🪷',
  'Streptocarpus ionanthus': '🪻',
  'Stromanthe thalia': '🌹',
  'Syngonium podophyllum': '🌱',
  'Thymus vulgaris': '☘️',
  'Tradescantia zebrina': '🪻',
  'Yucca gigantea': '🌴',
  'Zamioculcas zamiifolia': '🪴',
};

export function getPlantEmoji(
  scientificName: string | null | undefined,
) {
  if (!scientificName) {
    return '🪴';
  }

  return speciesEmojiMap[scientificName] ?? '🪴';
}

export { speciesEmojiMap };
